import scrapy

class iexpressEditorials(scrapy.Spider):
    name = "iexpress"
    start_urls = ['http://indianexpress.com/section/opinion/editorials/', 'http://indianexpress.com/section/opinion/editorials/page/2/', 'http://indianexpress.com/section/opinion/editorials/page/3/', 'http://indianexpress.com/section/opinion/editorials/page/4/', 'http://indianexpress.com/section/opinion/editorials/page/5/', 'http://indianexpress.com/section/opinion/editorials/page/6/', 'http://indianexpress.com/section/opinion/editorials/page/7/', 'http://indianexpress.com/section/opinion/editorials/page/8/', 'http://indianexpress.com/section/opinion/editorials/page/9/', 'http://indianexpress.com/section/opinion/editorials/page/10/', 'http://indianexpress.com/section/opinion/editorials/page/11/', 'http://indianexpress.com/section/opinion/editorials/page/12/', 'http://indianexpress.com/section/opinion/editorials/page/13/', 'http://indianexpress.com/section/opinion/editorials/page/14/', 'http://indianexpress.com/section/opinion/editorials/page/15/', 'http://indianexpress.com/section/opinion/editorials/page/16/', 'http://indianexpress.com/section/opinion/editorials/page/17/', 'http://indianexpress.com/section/opinion/editorials/page/18/', 'http://indianexpress.com/section/opinion/editorials/page/19/',
    'http://indianexpress.com/section/opinion/editorials/page/20/', 'http://indianexpress.com/section/opinion/editorials/page/21/', 'http://indianexpress.com/section/opinion/editorials/page/22/', 'http://indianexpress.com/section/opinion/editorials/page/23/', 'http://indianexpress.com/section/opinion/editorials/page/24/', 'http://indianexpress.com/section/opinion/editorials/page/25/', 'http://indianexpress.com/section/opinion/editorials/page/26/', 'http://indianexpress.com/section/opinion/editorials/page/27/', 'http://indianexpress.com/section/opinion/editorials/page/28/', 'http://indianexpress.com/section/opinion/editorials/page/29/', 'http://indianexpress.com/section/opinion/editorials/page/30/', 'http://indianexpress.com/section/opinion/editorials/page/31/', 'http://indianexpress.com/section/opinion/editorials/page/32/', 'http://indianexpress.com/section/opinion/editorials/page/33/', 'http://indianexpress.com/section/opinion/editorials/page/34/', 'http://indianexpress.com/section/opinion/editorials/page/35/', 'http://indianexpress.com/section/opinion/editorials/page/36/', 'http://indianexpress.com/section/opinion/editorials/page/37/', 'http://indianexpress.com/section/opinion/editorials/page/38/',
    'http://indianexpress.com/section/opinion/editorials/page/39/', 'http://indianexpress.com/section/opinion/editorials/page/40/', 'http://indianexpress.com/section/opinion/editorials/page/41/', 'http://indianexpress.com/section/opinion/editorials/page/42/', 'http://indianexpress.com/section/opinion/editorials/page/43/', 'http://indianexpress.com/section/opinion/editorials/page/44/', 'http://indianexpress.com/section/opinion/editorials/page/45/', 'http://indianexpress.com/section/opinion/editorials/page/46/', 'http://indianexpress.com/section/opinion/editorials/page/47/', 'http://indianexpress.com/section/opinion/editorials/page/48/', 'http://indianexpress.com/section/opinion/editorials/page/49/', 'http://indianexpress.com/section/opinion/editorials/page/50/', 'http://indianexpress.com/section/opinion/editorials/page/51/', 'http://indianexpress.com/section/opinion/editorials/page/52/', 'http://indianexpress.com/section/opinion/editorials/page/53/', 'http://indianexpress.com/section/opinion/editorials/page/54/', 'http://indianexpress.com/section/opinion/editorials/page/55/', 'http://indianexpress.com/section/opinion/editorials/page/56/', 'http://indianexpress.com/section/opinion/editorials/page/57/',
    'http://indianexpress.com/section/opinion/editorials/page/58/', 'http://indianexpress.com/section/opinion/editorials/page/59/', 'http://indianexpress.com/section/opinion/editorials/page/60/', 'http://indianexpress.com/section/opinion/editorials/page/61/', 'http://indianexpress.com/section/opinion/editorials/page/62/', 'http://indianexpress.com/section/opinion/editorials/page/63/', 'http://indianexpress.com/section/opinion/editorials/page/64/', 'http://indianexpress.com/section/opinion/editorials/page/65/', 'http://indianexpress.com/section/opinion/editorials/page/66/', 'http://indianexpress.com/section/opinion/editorials/page/67/', 'http://indianexpress.com/section/opinion/editorials/page/68/', 'http://indianexpress.com/section/opinion/editorials/page/69/', 'http://indianexpress.com/section/opinion/editorials/page/70/', 'http://indianexpress.com/section/opinion/editorials/page/71/', 'http://indianexpress.com/section/opinion/editorials/page/72/', 'http://indianexpress.com/section/opinion/editorials/page/73/', 'http://indianexpress.com/section/opinion/editorials/page/74/',
    'http://indianexpress.com/section/opinion/editorials/page/75/']

    def parse(self,respose):
        for href in respose.css('h6 a::attr(href)'):
          url = href.extract()
          yield scrapy.Request(url, callback = self.parse_item)


    def parse_item(self, response):
        yield {
        'ContentParagraph': response.css('p::text').extract(),
        'DateTime': response.css('#storycenterbyline span::text').extract(),
        'Headline': response.css('h1::text').extract(),
        'Author': response.css('#storycenterbyline a::text').extract()
        }
